<a href="https://colab.research.google.com/github/R-Guerra/Estudo/blob/main/Estudo_Reinforcement_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

- Aprendizado pro Reforço Utilizando Q-Learning com a Biblioteca Gym e Taxi-v3



Bibliotecas usadas:

In [ ]:
import numpy as np
import gym
import random
from IPython.display import clear_output
from time import sleep

Acessando a biblioteca Gym e usando o Taxi-v3

In [ ]:
env = gym.make("Taxi-v3").env
env.render()

+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+



Valores para a Tabela Q

In [ ]:
action_size = env.action_space.n
print("Action size ", action_size)

state_size = env.observation_space.n
print("State size ", state_size)

Action size  6
State size  500


Gerando a Tabela Q

In [ ]:
q_table = np.zeros((state_size, action_size))
print(q_table)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


Definindo os Hiperparâmetros e os Parâmetros de Exploração
 

In [ ]:
total_ep = 1000
total_test_ep = 100
max_steps = 100

lr = 0.81
gamma = 0.95

epsilon = 0.9
max_epsilon = 1.0
min_epsilon = 0.01
decay_rate = 0.01

Implementação do Algoritmo Q-Learning

In [ ]:
# Implementando o algoritmo Q-Learning

for episode in range(total_ep):

  # Redefinindo o ambiente
  state = env.reset()
  step = 0
  done = False

  for step in range(max_steps):

    # Escolha uma ação a no (s) estado (s) mundial (is) atual (s) (etapa 3)
    # Primeiro, randomizamos um número:
    exp_exp_tradeoff = random.uniform(0, 1)

    # Se este número> maior que épsilon -> exploração (considerando o maior valor q para o estado atual):
    if exp_exp_tradeoff > epsilon:
      action = np.argmax(q_table[state, :])

    # Caso contrário, escolha aleatória:
    else:
      action = env.action_space.sample()

    # Execute a ação (a) e observe o estado de resultado (s ') e a recompensa (r)
    new_state, reward, done, info = env.step(action)

    # Update Q(s,a):= Q(s,a) + lr [R(s,a) + gamma * max Q(s',a') - Q(s,a)]
    q_table[state, action] = q_table[state, action] + lr * (reward + gamma * 
                                    np.max(q_table[new_state, :]) - q_table[state, action])
    
    # Nosso novo estado:
    state = new_state

    # Se done True, termine o episódio:
    if done == True:
      break

  # Incrementando o número de episódios:
  episode += 1

  # Reduza o épsilon (porque precisamos cada vez menos de exploração):
  epsilon = min_epsilon + (max_epsilon - min_epsilon) *np.exp(-decay_rate*episode)

Utilização da Tabela Q

In [ ]:
# Usando a tabela Q (q_table):

env.reset()
rewards = []

for episode in range(total_test_ep):
  state = env.reset()
  step = 0
  done = False
  total_rewards = 0
  print('=========================')
  print('EPISÓDIO: ', episode)

  for step in range(max_steps):

    env.render()
    
    # Executando a ação com base na Tabela Q:
    action = np.argmax(q_table[state, :])

    new_state, reward, done, info = env.step(action)

    total_rewards += reward

    # Se o episódio terminar:
    if done:
      rewards.append(total_rewards)
      print('Pontos: ', total_rewards)
      break

    state = new_state

env.close()
print('Pontuação ao longo do tempo: {}'.format(sum(rewards)/total_test_ep))

A saída de streaming foi truncada nas últimas 5000 linhas.
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (South)
+---------+
|R: | : :G|
| : | : : |
| : : : : |
| | : | : |
|